[2025-06-12T09:10:03.646+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_pipeline.load_yfinance manual__2025-06-12T09:01:49.924358+00:00 [queued]>
[2025-06-12T09:10:03.665+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_pipeline.load_yfinance manual__2025-06-12T09:01:49.924358+00:00 [queued]>
[2025-06-12T09:10:03.666+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-06-12T09:10:03.704+0000] {taskinstance.py:1327} INFO - Executing <Task(DockerOperator): load_yfinance> on 2025-06-12 09:01:49.924358+00:00
[2025-06-12T09:10:03.712+0000] {standard_task_runner.py:57} INFO - Started process 270 to run task
[2025-06-12T09:10:03.719+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_pipeline', 'load_yfinance', 'manual__2025-06-12T09:01:49.924358+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/yfinance_pipeline_dag.py', '--cfg-path', '/tmp/tmp2hc5sajt']
[2025-06-12T09:10:03.721+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask load_yfinance
[2025-06-12T09:10:03.816+0000] {task_command.py:410} INFO - Running <TaskInstance: yfinance_pipeline.load_yfinance manual__2025-06-12T09:01:49.924358+00:00 [running]> on host c8950c9ffc98
[2025-06-12T09:10:03.992+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yfinance_pipeline' AIRFLOW_CTX_TASK_ID='load_yfinance' AIRFLOW_CTX_EXECUTION_DATE='2025-06-12T09:01:49.924358+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-12T09:01:49.924358+00:00'
[2025-06-12T09:10:04.091+0000] {docker.py:334} INFO - Starting docker container from image yfinance-load:latest
[2025-06-12T09:10:04.913+0000] {docker.py:403} INFO - 2025-06-12 09:10:04,911 - __main__ - INFO - ======================================================================
2025-06-12 09:10:04,911 - __main__ - INFO - ðŸš€ YFINANCE AUTO-LOAD TO 7 COLLECTIONS WITH DIFFERENT PERIODS
2025-06-12 09:10:04,911 - __main__ - INFO - ======================================================================
[2025-06-12T09:10:04.915+0000] {docker.py:403} INFO - 2025-06-12 09:10:04,911 - __main__ - INFO - Start time: 2025-06-12 09:10:04
2025-06-12 09:10:04,911 - __main__ - INFO - Loading from: /app/output/tickers_data.json
[2025-06-12T09:10:04.916+0000] {docker.py:403} INFO - 2025-06-12 09:10:04,912 - __main__ - INFO - Target database: bigdata_saham
[2025-06-12T09:10:04.916+0000] {docker.py:403} INFO - 2025-06-12 09:10:04,912 - __main__ - INFO - Target collections: ['data_harian', 'data_mingguan', 'data_bulanan', 'data_tahunan', 'data_lima_tahun', 'data_satu_tahun', 'data_tiga_tahun']
[2025-06-12T09:10:04.917+0000] {docker.py:403} INFO - 2025-06-12 09:10:04,913 - __main__ - ERROR - Failed to read input file /app/output/tickers_data.json: [Errno 2] No such file or directory: '/app/output/tickers_data.json'
[2025-06-12T09:10:04.917+0000] {docker.py:403} INFO - Traceback (most recent call last):
  File "/app/yfinance-load.py", line 373, in <module>
[2025-06-12T09:10:04.918+0000] {docker.py:403} INFO - result = load_to_all_collections()
  File "/app/yfinance-load.py", line 291, in load_to_all_collections
[2025-06-12T09:10:04.919+0000] {docker.py:403} INFO - with open(INPUT_FILE_PATH, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/output/tickers_data.json'
[2025-06-12T09:10:05.442+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 478, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 351, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 412, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 1} lines 2025-06-12 09:10:04,911 - __main__ - INFO - ======================================================================
2025-06-12 09:10:04,911 - __main__ - INFO - ðŸš€ YFINANCE AUTO-LOAD TO 7 COLLECTIONS WITH DIFFERENT PERIODS
2025-06-12 09:10:04,911 - __main__ - INFO - ======================================================================
2025-06-12 09:10:04,911 - __main__ - INFO - Start time: 2025-06-12 09:10:04
2025-06-12 09:10:04,911 - __main__ - INFO - Loading from: /app/output/tickers_data.json
2025-06-12 09:10:04,912 - __main__ - INFO - Target database: bigdata_saham
2025-06-12 09:10:04,912 - __main__ - INFO - Target collections: ['data_harian', 'data_mingguan', 'data_bulanan', 'data_tahunan', 'data_lima_tahun', 'data_satu_tahun', 'data_tiga_tahun']
2025-06-12 09:10:04,913 - __main__ - ERROR - Failed to read input file /app/output/tickers_data.json: [Errno 2] No such file or directory: '/app/output/tickers_data.json'
Traceback (most recent call last):
  File "/app/yfinance-load.py", line 373, in <module>
result = load_to_all_collections()
  File "/app/yfinance-load.py", line 291, in load_to_all_collections
with open(INPUT_FILE_PATH, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/output/tickers_data.json'
[2025-06-12T09:10:05.453+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=yfinance_pipeline, task_id=load_yfinance, execution_date=20250612T090149, start_date=20250612T091003, end_date=20250612T091005
[2025-06-12T09:10:05.494+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 26 for task load_yfinance (Docker container failed: {'StatusCode': 1} lines 2025-06-12 09:10:04,911 - __main__ - INFO - ======================================================================
2025-06-12 09:10:04,911 - __main__ - INFO - ðŸš€ YFINANCE AUTO-LOAD TO 7 COLLECTIONS WITH DIFFERENT PERIODS
2025-06-12 09:10:04,911 - __main__ - INFO - ======================================================================
2025-06-12 09:10:04,911 - __main__ - INFO - Start time: 2025-06-12 09:10:04
2025-06-12 09:10:04,911 - __main__ - INFO - Loading from: /app/output/tickers_data.json
2025-06-12 09:10:04,912 - __main__ - INFO - Target database: bigdata_saham
2025-06-12 09:10:04,912 - __main__ - INFO - Target collections: ['data_harian', 'data_mingguan', 'data_bulanan', 'data_tahunan', 'data_lima_tahun', 'data_satu_tahun', 'data_tiga_tahun']
2025-06-12 09:10:04,913 - __main__ - ERROR - Failed to read input file /app/output/tickers_data.json: [Errno 2] No such file or directory: '/app/output/tickers_data.json'
Traceback (most recent call last):
  File "/app/yfinance-load.py", line 373, in <module>
result = load_to_all_collections()
  File "/app/yfinance-load.py", line 291, in load_to_all_collections
with open(INPUT_FILE_PATH, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/output/tickers_data.json'; 270)
[2025-06-12T09:10:05.539+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-12T09:10:05.607+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
