[2025-06-11T15:59:10.723+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_pipeline.load_yfinance scheduled__2025-06-10T00:00:00+00:00 [queued]>
[2025-06-11T15:59:10.752+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_pipeline.load_yfinance scheduled__2025-06-10T00:00:00+00:00 [queued]>
[2025-06-11T15:59:10.753+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-06-11T15:59:10.801+0000] {taskinstance.py:1327} INFO - Executing <Task(DockerOperator): load_yfinance> on 2025-06-10 00:00:00+00:00
[2025-06-11T15:59:10.818+0000] {standard_task_runner.py:57} INFO - Started process 441 to run task
[2025-06-11T15:59:10.823+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_pipeline', 'load_yfinance', 'scheduled__2025-06-10T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/yfinance_pipeline_dag.py', '--cfg-path', '/tmp/tmp3h5kn58o']
[2025-06-11T15:59:10.827+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask load_yfinance
[2025-06-11T15:59:11.259+0000] {task_command.py:410} INFO - Running <TaskInstance: yfinance_pipeline.load_yfinance scheduled__2025-06-10T00:00:00+00:00 [running]> on host 08a50bba85ea
[2025-06-11T15:59:11.829+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yfinance_pipeline' AIRFLOW_CTX_TASK_ID='load_yfinance' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-10T00:00:00+00:00'
[2025-06-11T15:59:12.073+0000] {docker.py:334} INFO - Starting docker container from image yfinance-load:latest
[2025-06-11T15:59:14.008+0000] {docker.py:403} INFO - 2025-06-11 15:59:14,005 - __main__ - INFO - ======================================================================
2025-06-11 15:59:14,005 - __main__ - INFO - ðŸš€ YFINANCE AUTO-LOAD TO 7 COLLECTIONS WITH DIFFERENT PERIODS
2025-06-11 15:59:14,005 - __main__ - INFO - ======================================================================
[2025-06-11T15:59:14.010+0000] {docker.py:403} INFO - 2025-06-11 15:59:14,005 - __main__ - INFO - Start time: 2025-06-11 15:59:14
2025-06-11 15:59:14,005 - __main__ - INFO - Loading from: /app/output/tickers_data.json
[2025-06-11T15:59:14.011+0000] {docker.py:403} INFO - 2025-06-11 15:59:14,005 - __main__ - INFO - Target database: bigdata_saham
[2025-06-11T15:59:14.013+0000] {docker.py:403} INFO - 2025-06-11 15:59:14,005 - __main__ - INFO - Target collections: ['data_harian', 'data_mingguan', 'data_bulanan', 'data_tahunan', 'data_lima_tahun', 'data_satu_tahun', 'data_tiga_tahun']
[2025-06-11T15:59:35.275+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 478, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 351, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 412, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 137} lines 2025-06-11 15:59:14,005 - __main__ - INFO - ======================================================================
2025-06-11 15:59:14,005 - __main__ - INFO - ðŸš€ YFINANCE AUTO-LOAD TO 7 COLLECTIONS WITH DIFFERENT PERIODS
2025-06-11 15:59:14,005 - __main__ - INFO - ======================================================================
2025-06-11 15:59:14,005 - __main__ - INFO - Start time: 2025-06-11 15:59:14
2025-06-11 15:59:14,005 - __main__ - INFO - Loading from: /app/output/tickers_data.json
2025-06-11 15:59:14,005 - __main__ - INFO - Target database: bigdata_saham
2025-06-11 15:59:14,005 - __main__ - INFO - Target collections: ['data_harian', 'data_mingguan', 'data_bulanan', 'data_tahunan', 'data_lima_tahun', 'data_satu_tahun', 'data_tiga_tahun']
[2025-06-11T15:59:35.309+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=yfinance_pipeline, task_id=load_yfinance, execution_date=20250610T000000, start_date=20250611T155910, end_date=20250611T155935
[2025-06-11T15:59:35.360+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 12 for task load_yfinance (Docker container failed: {'StatusCode': 137} lines 2025-06-11 15:59:14,005 - __main__ - INFO - ======================================================================
2025-06-11 15:59:14,005 - __main__ - INFO - ðŸš€ YFINANCE AUTO-LOAD TO 7 COLLECTIONS WITH DIFFERENT PERIODS
2025-06-11 15:59:14,005 - __main__ - INFO - ======================================================================
2025-06-11 15:59:14,005 - __main__ - INFO - Start time: 2025-06-11 15:59:14
2025-06-11 15:59:14,005 - __main__ - INFO - Loading from: /app/output/tickers_data.json
2025-06-11 15:59:14,005 - __main__ - INFO - Target database: bigdata_saham
2025-06-11 15:59:14,005 - __main__ - INFO - Target collections: ['data_harian', 'data_mingguan', 'data_bulanan', 'data_tahunan', 'data_lima_tahun', 'data_satu_tahun', 'data_tiga_tahun']; 441)
[2025-06-11T15:59:35.392+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-11T15:59:35.439+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
